### ISSUE TITLE
jobs.BBCPipeline has get steps with the same name: plotgraph-resource

### ISSUE THREAD

**Issue by ravi432** [homedepot/BigBricks-core#50]
name="SearchEval"
env="hd-www-search"
zone="us-central1-c"
cloudWorkspace="gs://mosambi"
var solrprod = "solrprod"
var solrrelevance = "solrrelevance"
var solrstage = "solrstage"
var mosambi = "gs://mosambi/"
var work = mosambi+"work/"
var searchNavOutFolder = work + "searchnavout/"
var searchNavOutTextFolder = work + "searchnavouttext/"
var searchLogDatasets = "searchlogdatasets/"
var pythonFolder = work+"python/"
var evalFolder = work+"eval-reports/"
var weighted_word2vec = "weighted_word2vec"
var word2vec = "word2vec"
var tfidf = "tfidf"
artifactory hdartifactory {
    url="https://maven.artifactory.homedepot.com/artifactory"
    repository="libs-snapshot-local"
 }
sparkjob webRequestRunner(env,searchLogName) {
    mainClass="com.homedepot.bheem.services.MakeWebRequest"
    args= "--input",work+searchLogDatasets+searchLogName, "--output",searchNavOutFolder+env+"/"+searchLogName,
    "--partitions","25","--queryType",env
    jarLocation= % "com.homedepot.sa.el.search" % "bheem_2.11" % "2.1-SNAPSHOT" from hdartifactory
}
sparkjob webRequestToText(env,searchLogName) {
    mainClass="com.homedepot.bheem.intermediate.SearchNavJSONToText"
    args=  "--searchNav",searchNavOutFolder+env+"/"+searchLogName+"_good_*",
    "--output",searchNavOutTextFolder+env+"/"+searchLogName
    jarLocation= % "com.homedepot.sa.el.search" % "bheem_2.11" % "2.1-SNAPSHOT" from hdartifactory
}
cluster devClusterSearchRelevance {
    workers=3
    image="n1-standard-2"
    properties="spark:spark.executor.cores=2"
}
cluster prodClusterSearchRelevance {
    workers=4
    image="n1-standard-4"
    properties="spark:spark.executor.cores=4"
    initialScript = pythonFolder+"pyspark-search-eval-init.sh"
    initialScriptTimeOut = "600s"
}
pysparkjob twoway(env1,env2,searchLogName,algorithm) {
    mainPyFile=pythonFolder+"twowaysimilarity_spark.py"
    otherPyFiles= pythonFolder+"spark_wrapper.py",
    pythonFolder+"readers.py",pythonFolder+"custom_tokenize.py", pythonFolder+"text_similarity.py"
    args="--firstFile",searchNavOutTextFolder+env1+"/"+searchLogName,
    "--secondFile",searchNavOutTextFolder+env2+"/"+searchLogName,
    "--word2vecModel",pythonFolder+"models/word2vec_spark_v1.0",
    "--tfidfModel",pythonFolder+"models/tfidf_spark_v1.0",
    "--cvModel",pythonFolder+"models/cv_spark_v1.0",
    "--firstTag",env1,
    "--secondTag",env2,
    "--vectorAlgorithm",algorithm,
    "--outputFolder",evalFolder+algorithm+searchLogName
    }
pysparkjob aggregatetwoway(env1, env2,searchLogName) {
    mainPyFile=pythonFolder+"aggregate_similarities_spark.py"
    otherPyFiles= pythonFolder+"spark_wrapper.py",
    pythonFolder+"readers.py",pythonFolder+"custom_tokenize.py", pythonFolder+"text_similarity.py"
    args="--firstTag",env1,"--secondTag",env2,
    "--outputFolder",evalFolder+"aggregated-twoway"+env1+env2+searchLogName,
    "--inputFolders",evalFolder+weighted_word2vec+searchLogName+"/*"+
    ","+evalFolder+word2vec+searchLogName+"/*"
    }
pythonjob plotgraph (tag1, tag2,searchLog) {
    mainPyFile="src/plot_two_way_summary.py"
    repository= "git@github.homedepot.com:OLT-search/Kabali.git"
    repoBranch="master"
    container="ksrpk/python-gensim-gcloud"
    args = "--firstTag",tag1, "--secondTag",tag2,"--vectorAlgorithms","word2vec,weighted_word2vec","--inputFile","gs://mosambi/work/eval-reports/aggregated-twoway"+tag1+tag2+searchLog+"/"+tag1+"-"+tag2+"summary.csv"
}
pipeline twowaypipe(searchLog){
    run webRequestRunner(solrstage,searchLog) on prodClusterSearchRelevance
    run webRequestRunner(solrprod,searchLog) on prodClusterSearchRelevance
    run webRequestToText(solrstage,searchLog) on prodClusterSearchRelevance
    run webRequestToText(solrprod,searchLog) on prodClusterSearchRelevance
    run twoway(solrprod,solrstage,searchLog,"weighted_word2vec") on prodClusterSearchRelevance
    run twoway(solrprod,solrstage,searchLog,"word2vec") on prodClusterSearchRelevance
    run aggregatetwoway(solrprod,solrstage,searchLog) on prodClusterSearchRelevance
    
}
run twowaypipe("All-50k-morethan50.txt")
run plotgraph(solrprod,solrstage,"All-50k-morethan50.txt")

run twowaypipe("Semantic-nlprulebased-100k")
run plotgraph(solrprod,solrstage,"Semantic-nlprulebased-100k")

**Comment by ravi432** [comment]
Not able run two plot graphs

**Comment by feroshjacob** [comment]
Another case 
`name="CreateDataTest"
env="hd-www-search"
zone="us-east1-c"
cloudWorkspace="gs://mosambi"

    var mosambi = "gs://mosambi"
    var output = "temp"
    pysparkjob example1 {
        mainPyFile="gs://mosambi/work/python/twowaysimilarity_spark.py"
        otherPyFiles= ""
    }
    cluster simpleCluster {
        workers=2
        image="n1-standard-2"
        properties="spark:spark.executor.cores=2"
        initialScript = "gs://mosambi/work/python/pyspark-search-eval-init.sh"
        initialScriptTimeOut = "600s"

    }
        pythonjob example2 {
                 mainPyFile="src/two_way_similarity.py"
                 repository= "git@github.homedepot.com:OLT-search/Judas.git"
                 repoBranch="master"
                 container="ksrpk/python-gensim-gcloud"
                 args = "--this", "will", "--may", "work"
                 }
        run example1 on simpleCluster`

This causes error 

**error: invalid configuration:
invalid resources:
	resource 'example2-resource' is not used**
